// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1sU5ncxH3c6Y1E6XxBe0rXEL_eMiXJRQ',
    appId: '1:973871830139:web:46cbf3c8dffd6bae21fede',
    messagingSenderId: '973871830139',
    projectId: 'bfp-emergency',
    authDomain: 'bfp-emergency.firebaseapp.com',
    storageBucket: 'bfp-emergency.firebasestorage.app',
    measurementId: 'G-72L5QQYLSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkEUi5J6S1h4taoouekYwV5KBguQ_6Amg',
    appId: '1:973871830139:android:cd6896cbc364f98621fede',
    messagingSenderId: '973871830139',
    projectId: 'bfp-emergency',
    storageBucket: 'bfp-emergency.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzLCa0m-OaUDcMzX7sdMIL-Zmz4zbaq4U',
    appId: '1:973871830139:ios:b6da58d2184353ab21fede',
    messagingSenderId: '973871830139',
    projectId: 'bfp-emergency',
    storageBucket: 'bfp-emergency.firebasestorage.app',
    iosBundleId: 'com.example.bfpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzLCa0m-OaUDcMzX7sdMIL-Zmz4zbaq4U',
    appId: '1:973871830139:ios:b6da58d2184353ab21fede',
    messagingSenderId: '973871830139',
    projectId: 'bfp-emergency',
    storageBucket: 'bfp-emergency.firebasestorage.app',
    iosBundleId: 'com.example.bfpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1sU5ncxH3c6Y1E6XxBe0rXEL_eMiXJRQ',
    appId: '1:973871830139:web:2703c0681fac4cc721fede',
    messagingSenderId: '973871830139',
    projectId: 'bfp-emergency',
    authDomain: 'bfp-emergency.firebaseapp.com',
    storageBucket: 'bfp-emergency.firebasestorage.app',
    measurementId: 'G-8L6C4K9EGH',
  );
}
